module Generators::Jbuilder
  module Config
    cattr_accessor :enable do
      true
    end

    cattr_accessor :overwrite do
      false
    end

    cattr_accessor :templates do
      {
          index: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            unless @status
              render_error
              json.partial! 'api/base', total: 0
              return
            end

            json.partial! 'api/base', total: @data.size
  
            # @data = @data.page(@page).per(@rows) if @page || @row
            # json.data @data.to_a.to_builder
            json.data @data.page(@page).per(@rows).to_a.to_builder
          FILE
          ),

          cache_index: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            unless @status
              render_error
              json.partial! 'api/base', total: 0
              return
            end

            json.partial! 'api/base', total: @data.size
  
            # @data = @data.page(@page).per(@rows) if @page || @row
            json.cache! [ 'TODO: key' ], expires_in: 10.minutes do
              # json.data @data.to_a.to_builder
              json.data @data.page(@page).per(@rows).to_a.to_builder
            end
          FILE
          ),

          show: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            total = 0 and render_error if @status == false
    
            json.partial! 'api/base', total: total || 1
            json.data @datum&.to_builder
          FILE
          ),

          cache_show: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            total = 0 and render_error if @status == false
    
            json.partial! 'api/base', total: total || 1
    
            json.cache! [ 'TODO: key' ], expires_in: 10.minutes do
              json.datum @datum&.to_builder
            end
          FILE
          ),

          success: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            json.partial! 'api/success'
          FILE
          ),

          success_or_not: (
          <<~FILE
            # *** Generated by Zero [ please make sure that you have checked this file ] ***
    
            render_error if @status == false
    
            json.partial! 'api/base', total: 0
          FILE
          ),
      }
    end
  end
end
